version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  node: circleci/node@4.7.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_push_docker:
    docker:
      - image: cimg/node:16.20
    steps:
      - attach_workspace:
          at: ~/project
      - aws-cli/setup:
          profile-name: "default"
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_DEFAULT_REGION
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t circleci-demo .
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - run:
          name: Tag and Push Docker Image
          command: |
            docker tag circleci-demo:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/circleci-demo:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/circleci-demo:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker:
          requires:
            - build_and_test






# version: 2.1
# orbs:
#   node: circleci/node@4.7.0
#   heroku: circleci/heroku@1.2.6

# jobs:
#   build_and_test:
#     docker:
#       - image: cimg/node:17.2.0
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: yarn
#       - run:
#           command: yarn test
#           name: Run tests
#       - run:
#           command: yarn build
#           name: Build app
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - .
#   deploy: # this can be any name you choose
#     docker:
#       - image: cimg/node:17.2.0
#     steps:
#       - attach_workspace:
#           at: ~/project
#       - heroku/deploy-via-git: 
#           force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

# workflows:
#   on_commit:
#     jobs:
#       - build_and_test
#       # Follow instructions here to authenticate git for Heroku: https://devcenter.heroku.com/articles/git#http-git-authentication
#       # The following code may be uncommented, onnce HEROKU_API_KEY & HEROKU_APP_NAME environemnt variables are present
#       # Read more: https://circleci.com/docs/2.0/env-vars/
#       # - deploy:
#       #     requires:
#       #       - build_and_test # only deploy if the build_and_test job has completed
#       #     filters:
#       #       branches:
#       #         only: master # only deploy when on main/master
#   nightly:
#     triggers:
#       - schedule:
#           cron: "0 0 * * *"       
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - build_and_test
#       # Follow instructions here to authenticate git for Heroku: https://devcenter.heroku.com/articles/git#http-git-authentication
#       # The following code may be uncommented, onnce HEROKU_API_KEY & HEROKU_APP_NAME environemnt variables are present
#       # Read more: https://circleci.com/docs/2.0/env-vars/
#       # - deploy:
#       #     requires:
#       #       - build_and_test # only deploy if the build_and_test job has completed
#       #     filters:
#       #       branches:
#       #         only: master # only deploy when on main/master
